/**
 * Utility functions for formatting data in tables and displays
 */

/**
 * Format a date string for table display
 * @param dateStr - ISO date string
 * @returns Formatted date string (e.g., "Jan 15, 2025")
 */
export const formatTableDate = (dateStr: string): string => {
  try {
    return new Date(dateStr).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    });
  } catch (error) {
    return dateStr;
  }
};

/**
 * Format a number with thousands separators and specified decimals
 * @param value - Number to format
 * @param decimals - Number of decimal places (default: 2)
 * @returns Formatted number string
 */
export const formatTableNumber = (value: number, decimals: number = 2): string => {
  if (value === null || value === undefined || isNaN(value)) {
    return '-';
  }

  return value.toLocaleString('en-US', {
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals
  });
};

/**
 * Format a number as currency (USD)
 * @param value - Number to format
 * @returns Formatted currency string (e.g., "$1,234.56")
 */
export const formatCurrency = (value: number): string => {
  if (value === null || value === undefined || isNaN(value)) {
    return '-';
  }

  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2
  }).format(value);
};

/**
 * Check if a column is synthetic (generated by the system)
 * @param columnName - Name of the column to check
 * @param syntheticColumns - Array of synthetic column names
 * @returns True if the column is synthetic
 */
export const isSyntheticColumn = (
  columnName: string,
  syntheticColumns: string[]
): boolean => {
  return syntheticColumns.includes(columnName);
};
